spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb+srv://samanthd2004_db_user:sam%40database@cluster0.qe9yjnx.mongodb.net/fitnessrecommendation

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
    key: "AIzaSyAvEg6L_jGsmbqLHSpJczRpAQbvtG3Vlv8"


server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
